import React from 'react';
import Head from 'next/head';
import Header from '../../components/Header';
<<<<<<<<< Temporary merge branch 1
import kueski_fondo from '@/public/imagenes/kueski_fondo.png';
import { useRouter } from 'next/router';
=========
import Acceso from '@/components/Acceso';
>>>>>>>>> Temporary merge branch 2

{/* Pagina de Acceso */}

const Acceso = () => {
  const router = useRouter();
  const { userId } = router.query;

  return (
    <>
      <Head>
        <title>Acceso</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
<<<<<<<<< Temporary merge branch 1
      <Header />
      <h1 className='p-4'>Acceso</h1>
      <main className='bg-gray-100 min-h-screen' style={{backgroundImage: `url(${kueski_fondo})`}}>
        <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>

          </div>
        </div>
      </main>
=========
        <Header />
        <h1 className='p-4'>HOME</h1>
        <Acceso/>
        
>>>>>>>>> Temporary merge branch 2
    </>
  );
};

export default Acceso;
