import React from 'react';
import Head from 'next/head';
import Header from '../../components/Header';
import Acceso from '@/components/Acceso';

{/* Pagina de INICIO */}

const Home = () => {
  return (
    <>
      <Head>
        <title>Welcome Kueski</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
        <Header />
        <h1 className='p-4'>HOME</h1>
        <Acceso/>
        
    </>
  );
};

export default Home;