import React from 'react';
import Head from 'next/head';
import Header from '../../components/Header';
import { useRouter } from 'next/router';
import CancelacionCom from '@/components/CancelacionCom';
import Advertencia from '@/components/Advertencia';

const Cancelacion = () => {
  const router = useRouter();
  const { userid } = router.query;

  return (
    <>
      <Head>
        <title>Acceso</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <Header />
      <h1 className='text-lg font-bold p-4'>Cancelación</h1>
      <div className='p-4'>
        {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
        {/*<h2>UserID: {userid}</h2>*/}
        <div className='flex flex-col items-center'>
          <Advertencia />
          <CancelacionCom searchIndex={userid} />
        </div>
      </div>
    </>
  );
};

export default Cancelacion;