import React from 'react';
import Head from 'next/head';
import Header from '../../components/Header';
import { useRouter } from 'next/router';
import Historialcom from '@/components/Historialcom';
{/* Pagina de Acceso */}

const Historial = () => {
  const router = useRouter();
  const { idrequest } = router.query;

  return (
    <>
      <Head>
        <title>Historial</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <Header />
      <h1 className='p-4'>Acceso</h1>
      <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>
            <h2>UserID: {idrequest}</h2>
          </div>
      </div>
      <Historialcom searchIndex={idrequest}/>
    </>
  );
};

export default Historial;