import React from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import kueski_fondo from '../public/imagenes/kueski_fondo.png';
import Welcome from '@/components/Welcome';

const Home = () => {
    let ComponentToRender;
    switch (selectedComponent) {
        case 'Oposicion':
        ComponentToRender = Oposicion;
        break;
        case 'Acceder':
        ComponentToRender = Acceder;
        break;
        case 'Rectificar':
        ComponentToRender = Rectificar;
        break;
        case 'Cancelar':
        ComponentToRender = Cancelar;
        break;
        default:
        ComponentToRender = Hidder;
  }
  return (
    <>
      <Head>
        <title>Welcome Kueski</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
        <Header />
        <h1 className='p-4'>Bienvenido</h1>
        <Welcome/>
        <main className='bg-gray-100 min-h-screen' style={{backgroundImage: `url(${kueski_fondo})`}}>

        <div className='p-4'>
            <section id="Operations" className='mt-24'>
                <h1 className='p-4'>Operaciones ARCO:</h1>
                <div className='mt-12 align-center bg-white'>
                  <ComponentToRender/>
                </div>
            </section>
        </div>
      </main>
    </>
  );
};

export default Home;