
import React, { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Searchbar from '../components/Searchbar';
import Visualizer from '../components/Visualizer';
import Hidder from '../components/Hidder';



const Home = () => {
  const [selectedComponent, setSelectedComponent] = useState(Hidder);
  const [searchValue, setSearchValue] = useState("");
  const handleSearchChange = (value) => {
    console.log("Valor de searchValue en dashboard.js:", value);
    setSearchValue(value);
  };

  const handleButtonClick = (component) => {
    setSelectedComponent(component);
  };

  

  return (
    <>
      <Head>
        <title>Kueski Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <section className='flex justify-between px-4 pt-4'>          
        <h1 className='p-4'>Dashboard</h1>
        <Header />
        </section>
        
        <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>
            {/* Agregamos la clase w-full para que el searchbar ocupe todo el ancho del contenedor */}
            <div className='w-full mt-8'>
              <Searchbar onSearchChange={handleSearchChange} />
            </div>
            {/* Agregamos la clase mt-4 para crear un margen superior de 16px */}
            <div className='mt-4 z-10'>
              <Visualizer searchValue={searchValue} onButtonClick={handleButtonClick} />
            </div>
            
          </div>
        </div>
      </main>
    </>
  );
};
export default Home;