
import React, { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Searchbar from '../components/Searchbar';
import Visualizer from '../components/Visualizer';

const Home = () => {
  const [searchValue, setSearchValue] = useState("");
  const handleSearchChange = (value) => {
    console.log("Valor de searchValue en dashboard.js:", value);
    setSearchValue(value);
  };


  return (
    <>
      <Head>
        <title>Kueski Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>
            {/* Agregamos la clase w-full para que el searchbar ocupe todo el ancho del contenedor */}
            <div className='w-full mt-8'>
              <Searchbar onSearchChange={handleSearchChange} />
            </div>
            {/* Agregamos la clase mt-4 para crear un margen superior de 16px */}
            <div className='mt-4 z-10'>
              <Visualizer searchValue={searchValue} />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};
export default Home;