
import React, { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Searchbar from '../components/Searchbar';
import Visualizer from '../components/Visualizer';
import Oposicion from '../components/Oposicion';
import Acceder from '../components/Acceso';
import Rectificar from '../components/Rectificacion';
import Cancelar from '../components/Cancelacion';
import Hidder from '../components/Hidder';

const Home = () => {
  const [selectedComponent, setSelectedComponent] = useState(Hidder);
  const [searchValue, setSearchValue] = useState("");
  const handleSearchChange = (value) => {
    console.log("Valor de searchValue en dashboard.js:", value);
    setSearchValue(value);
  };

  const handleButtonClick = (component) => {
    setSelectedComponent(component);
  };

  let ComponentToRender;
  switch (selectedComponent) {
    case 'Oposicion':
      ComponentToRender = Oposicion;
      break;
    case 'Acceder':
      ComponentToRender = Acceder;
      break;
    case 'Rectificar':
      ComponentToRender = Rectificar;
      break;
    case 'Cancelar':
      ComponentToRender = Cancelar;
      break;
    default:
      ComponentToRender = Hidder;
  }

  return (
    <>
      <Head>
        <title>Kueski Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>
            {/* Agregamos la clase w-full para que el searchbar ocupe todo el ancho del contenedor */}
            <div className='w-full'>
              <Searchbar onSearchChange={handleSearchChange} />
            </div>
            {/* Agregamos la clase mt-4 para crear un margen superior de 16px */}
            <div className='mt-4 z-10'>
              <Visualizer searchValue={searchValue} onButtonClick={handleButtonClick} />
              <h1 className='p-4'>Operaciones ARCO:</h1>
              <div className='mt-4 align-center bg-white'>
                <ComponentToRender/>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;