
import React, { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Searchbar from '../components/Searchbar';
import Visualizer from '../components/Visualizer';
import Oposicion from '../components/Oposicion';
import Acceder from '../components/Acceso';
import Rectificar from '../components/Rectificacion';
import Cancelar from '../components/Cancelacion';

const Home = () => {
  const [selectedComponent, setSelectedComponent] = useState('Oposicion');

  const handleButtonClick = (component) => {
    setSelectedComponent(component);
  };

  let ComponentToRender;
  switch (selectedComponent) {
    case 'Oposicion':
      ComponentToRender = Oposicion;
      break;
    case 'Acceder':
      ComponentToRender = Acceder;
      break;
    case 'Rectificar':
      ComponentToRender = Rectificar;
      break;
    case 'Cancelar':
      ComponentToRender = Cancelar;
      break;
    default:
      ComponentToRender = Oposicion;
  }

  return (
    <>
      <Head>
        <title>Kueski Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/kueskiLogo.png' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <div className='p-4'>
          {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado */}
          <div className='flex flex-col'>
            {/* Agregamos la clase w-full para que el searchbar ocupe todo el ancho del contenedor */}
            <div className='w-full'>
              <Searchbar />
            </div>
            {/* Agregamos la clase mt-4 para crear un margen superior de 16px */}
            <div className='mt-4 z-10'>
              <Visualizer onButtonClick={handleButtonClick} />
              <h1>Operaciones ARCO:</h1>
              <div className='mt-4 align-center bg-white'>
                <ComponentToRender />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

{/*
//import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'
//Importar sql
import { useEffect, useState } from 'react';

import Header from '../components/Header'
import Visualizer from '../components/Visualizer'
import Searchbar from '../components/SearchBar'
import Acceso from '@/components/Acceso';
import Rectificacion from '@/components/Rectificacion';
import Cancelacion from '@/components/Cancelacion';
import Oposicion from '@/components/Oposicion';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //Array de resultados del query
  const [dataResult, setdataResult] = useState([]);
  //funcion para hacer fetch y llenar el array
  useEffect(() => {
    async function getPageData(){
      const apiUrlEndpoint = "http://localhost:3000/api/getData";
      const response = await fetch(apiUrlEndpoint);
      const res = await response.json();
      //console.log(res.names);
      setdataResult(res.names);
    }
    //Corremos la funcion
    getPageData();
  }, []);
  return (
    <>
      <Head>
        <title>Kueski Dashboard</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link rel='icon' href='/kueskiLogo.png'/>
      </Head>
      <main className='bg-gray-100 min-h-screen'>
      <Header />
      <div className='p-4'>
        {/* Agregamos las clases flex flex-col items-center para crear un contenedor flexible vertical y centrado *
        <div className='flex flex-col'>
          {/* Agregamos la clase w-full para que el searchbar ocupe todo el ancho del contenedor *
          <div className='w-full'>
            <Searchbar/>
          </div>
          {/* Agregamos la clase mt-4 para crear un margen superior de 16px *
          <div className='mt-4 z-10'>
          <Visualizer/>
          <h1>Operaciones ARCO:</h1>
            <div className='mt-4 align-center bg-white'>
              <Oposicion/>
            </div>
          </div>
        </div>
      </div>
      </main>
    </>
  )
}

*/}
